/*
 * configuration management API  - OpenAPI 3.0
 *
 * use this to manage configurations.
 *
 * API version: 0.0.1
 * Contact: william.ohara@subscripify.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package configsapi

type AccessConfigPatchBody struct {
	// The alias name does not need to be unique and is used for quick reference when searching in UI. No starting spaces and no special characters.
	Alias string `json:"alias,omitempty"`
	// The access level can change
	AccessConfigDeploymentLevel string `json:"accessConfigDeploymentLevel,omitempty"`
}
