/*
 * configuration management API  - OpenAPI 3.0
 *
 * use this to manage configurations.
 *
 * API version: 0.0.1
 * Contact: william.ohara@subscripify.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package configsapi

type TenantConfigCreateBody struct {
	// The config UUID to use for the new config. Must be a valid services config UUID
	TenantConfigUUID string `json:"tenantConfigUUID,omitempty"`
	// The alias name does not need to be unique and is used for quick reference when searching in UI. No starting spaces and no special characters.
	ConfigAlias string `json:"configAlias,omitempty"`
	// the cloud provider location.
	ConfigLocation string `json:"configLocation,omitempty"`
	// Tthe UUID for the owning tenant. This config can only be applied to the owner tenant or any of its vassal tenants
	OwnerUUID string `json:"ownerUUID,omitempty"`
	// the person who created the tenant
	CreatedBy string `json:"createdBy,omitempty"`
	// the deployment level of the new config.
	DeploymentLevel string `json:"deploymentLevel,omitempty"`
}
