/*
 * configuration management API  - OpenAPI 3.0
 *
 * use this to manage configurations.
 *
 * API version: 0.0.1
 * Contact: william.ohara@subscripify.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package configsapi

type HttpResponseMessage struct {

	ResponseCode int32 `json:"responseCode,omitempty"`

	Message string `json:"message,omitempty"`
}
