/*
 * configuration management API  - OpenAPI 3.0
 *
 * use this to manage configurations.
 *
 * API version: 0.0.1
 * Contact: william.ohara@subscripify.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package configsapi

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"AddAccessConfig",
		strings.ToUpper("Post"),
		"/access-config",
		AddAccessConfig,
	},

	Route{
		"DeleteAccessConfig",
		strings.ToUpper("Delete"),
		"/access-config/{targetUUID}",
		DeleteAccessConfig,
	},

	Route{
		"GetAccessConfig",
		strings.ToUpper("Get"),
		"/access-config/{targetUUID}",
		GetAccessConfig,
	},

	Route{
		"SearchAccessConfig",
		strings.ToUpper("Get"),
		"/search/access-config",
		SearchAccessConfig,
	},

	Route{
		"UpdateAccessConfig",
		strings.ToUpper("Patch"),
		"/access-config/{targetUUID}",
		UpdateAccessConfig,
	},

	Route{
		"AddTenantConfig",
		strings.ToUpper("Post"),
		"/tenant-config",
		AddTenantConfig,
	},

	Route{
		"DeleteTenantConfig",
		strings.ToUpper("Delete"),
		"/tenant-config/{targetUUID}",
		DeleteTenantConfig,
	},

	Route{
		"GetTenantConfig",
		strings.ToUpper("Get"),
		"/tenant-config/{targetUUID}",
		GetTenantConfig,
	},

	Route{
		"SearchTenantConfig",
		strings.ToUpper("Get"),
		"/search/tenant-config",
		SearchTenantConfig,
	},

	Route{
		"UpdateTenantConfig",
		strings.ToUpper("Patch"),
		"/tenant-config/{targetUUID}",
		UpdateTenantConfig,
	},
}
